services:
  postgres:
    image: postgres:16-alpine
    container_name: clen_postgres
    environment:
      POSTGRES_USER: clen_user
      POSTGRES_PASSWORD: clenshop
      POSTGRES_DB: clen_catalog
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: