// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/catalog/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Входящие данные
type CheckProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // В protobuf нет UUID, используем строку
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductRequest) Reset() {
	*x = CheckProductRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductRequest) ProtoMessage() {}

func (x *CheckProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductRequest.ProtoReflect.Descriptor instead.
func (*CheckProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CheckProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

//Исходящие данные
type CheckProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"` // Текущая цена (важно, чтобы юзер не заказал по старой цене)
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"` // Остаток на складе
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`    // Название для отображения в корзине
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductResponse) Reset() {
	*x = CheckProductResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductResponse) ProtoMessage() {}

func (x *CheckProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductResponse.ProtoReflect.Descriptor instead.
func (*CheckProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CheckProductResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckProductResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CheckProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CheckProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_catalog_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/catalog.proto\x12\acatalog\"4\n" +
	"\x13CheckProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"n\n" +
	"\x14CheckProductResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name2]\n" +
	"\x0eCatalogService\x12K\n" +
	"\fCheckProduct\x12\x1c.catalog.CheckProductRequest\x1a\x1d.catalog.CheckProductResponseB.Z,catalog-service/pkg/api/catalog/v1;catalogv1b\x06proto3"

var (
	file_proto_catalog_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_catalog_proto_rawDescData []byte
)

func file_proto_catalog_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_catalog_proto_rawDescData
}

var file_proto_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_catalog_catalog_proto_goTypes = []any{
	(*CheckProductRequest)(nil),  // 0: catalog.CheckProductRequest
	(*CheckProductResponse)(nil), // 1: catalog.CheckProductResponse
}
var file_proto_catalog_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.CatalogService.CheckProduct:input_type -> catalog.CheckProductRequest
	1, // 1: catalog.CatalogService.CheckProduct:output_type -> catalog.CheckProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_catalog_catalog_proto_init() }
func file_proto_catalog_catalog_proto_init() {
	if File_proto_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_catalog_proto = out.File
	file_proto_catalog_catalog_proto_goTypes = nil
	file_proto_catalog_catalog_proto_depIdxs = nil
}
