// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/cart.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/cart.go -destination=internal/usecase/mocks/mock_catalog.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "order-service/internal/domain"
	usecase "order-service/internal/usecase"
	catalogv1 "order-service/pkg/api/catalog/v1"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCartUseCase is a mock of CartUseCase interface.
type MockCartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCartUseCaseMockRecorder
	isgomock struct{}
}

// MockCartUseCaseMockRecorder is the mock recorder for MockCartUseCase.
type MockCartUseCaseMockRecorder struct {
	mock *MockCartUseCase
}

// NewMockCartUseCase creates a new mock instance.
func NewMockCartUseCase(ctrl *gomock.Controller) *MockCartUseCase {
	mock := &MockCartUseCase{ctrl: ctrl}
	mock.recorder = &MockCartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartUseCase) EXPECT() *MockCartUseCaseMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCartUseCase) AddToCart(ctx context.Context, input usecase.AddToCartInput) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, input)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartUseCaseMockRecorder) AddToCart(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCartUseCase)(nil).AddToCart), ctx, input)
}

// ClearCart mocks base method.
func (m *MockCartUseCase) ClearCart(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockCartUseCaseMockRecorder) ClearCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockCartUseCase)(nil).ClearCart), ctx, userID)
}

// GetCart mocks base method.
func (m *MockCartUseCase) GetCart(ctx context.Context, userID uuid.UUID) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartUseCaseMockRecorder) GetCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartUseCase)(nil).GetCart), ctx, userID)
}

// MockCatalogProvider is a mock of CatalogProvider interface.
type MockCatalogProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogProviderMockRecorder
	isgomock struct{}
}

// MockCatalogProviderMockRecorder is the mock recorder for MockCatalogProvider.
type MockCatalogProviderMockRecorder struct {
	mock *MockCatalogProvider
}

// NewMockCatalogProvider creates a new mock instance.
func NewMockCatalogProvider(ctrl *gomock.Controller) *MockCatalogProvider {
	mock := &MockCatalogProvider{ctrl: ctrl}
	mock.recorder = &MockCatalogProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogProvider) EXPECT() *MockCatalogProviderMockRecorder {
	return m.recorder
}

// CheckProduct mocks base method.
func (m *MockCatalogProvider) CheckProduct(ctx context.Context, productID string) (*catalogv1.CheckProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProduct", ctx, productID)
	ret0, _ := ret[0].(*catalogv1.CheckProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProduct indicates an expected call of CheckProduct.
func (mr *MockCatalogProviderMockRecorder) CheckProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProduct", reflect.TypeOf((*MockCatalogProvider)(nil).CheckProduct), ctx, productID)
}
